name: Create and publish a container image

on:
  push:
    # Publish main branch as `develop` image
    branches:
      - main

    # Publish tags as versioned release and `latest` image
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        # Need fetch-depth 0 to fetch tags, see https://github.com/actions/checkout/issues/701
        with:
          fetch-depth: 0

      - name: Gather context
        id: ctx
        run: |
          echo is_release=${{ contains(github.ref, 'refs/tags/') }} | tee -a $GITHUB_OUTPUT
          echo is_dev=${{ ! contains(github.ref, 'refs/tags/') }} | tee -a $GITHUB_OUTPUT
          echo version=$(git describe --tags | cut -d '-' -f -2 | sed 's/-/.dev/g') | tee -a $GITHUB_OUTPUT

      # QEMU is used to set up VMs for building non-x86_64 images.
      - name: Set up QEMU
        uses: step-security/setup-qemu-action@8c4aef027ab2df56e08f597afe6dd8cd31cb84f5 # v3.7.0
        with:
          platforms: "arm,arm64"

      # This is required to build multi-arch images.
      - name: Set up Docker Buildx
        uses: step-security/setup-buildx-action@f931205d68723ad9589fd2a7e2ece238bf9de341 # v4.0.0

      - name: Log in to registry
        uses: step-security/docker-login-action@6aa05fe688caf2c58e784663f01b3415ced503e8 # v3.7.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure metadata
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # Configure to use `latest` and the PEP440 version from a tag name for
          # releases, and `develop` for non-release main builds.
          tags: |
            type=pep440,pattern={{ version }},enable=${{ steps.ctx.outputs.is_release }}
            type=raw,value=latest,enable=${{ steps.ctx.outputs.is_release }}
            type=raw,value=develop,enable=${{ steps.ctx.outputs.is_dev }}
          labels: |
            org.opencontainers.image.authors=opensource@aiven.io
            org.opencontainers.image.url=https://karapace.io
            org.opencontainers.image.documentation=https://github.com/Aiven-Open/karapace/
            org.opencontainers.image.vendor=Aiven
            org.opencontainers.image.licenses=Apache-2.0

      - uses: step-security/docker-build-push-action@a8c3d08b23f8be6aeed43eb1a14ce6fe51284438 # v6.18.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            KARAPACE_VERSION=${{ steps.ctx.outputs.version }}
          file: container/Dockerfile
          platforms: "linux/amd64,linux/arm64"
